### ISSUE TITLE
Git won't clone repo via git://github.com/mireq/buildroot-a13-olinuxino

### ISSUE THREAD

**Issue by Hid-K** [mireq/a13-olinuxino-autobuild#1]

**Comment by Hid-K** [comment]
The solution is to replace 'git://github.com/mireq/buildroot-a13-olinuxino' with 'https://github.com/messense/homebrew-macos-cross-toolchains.git'

**Comment by mireq** [comment]
Currently i don't have hardware to test with another toolchain, i am just changing old git (not working) URL to https.
